name: R Testing

on:
  push:
    branches: [ "*" ]
    tags: [ "*" ]

jobs:
  test-r:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.6

      - name: Install R and dependencies
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.1' # Specify your desired R version

      - name: Install R package dependencies
        run: |
          Rscript -e "install.packages('adegenet')"

      - name: Test run R script
        run: Rscript test_script.R
